<div class="right">
    <?php echo $this->ajax('back', 'chat/room', 2) ?>
</div>
<div class="room">
<?php echo $this->form?>
</div>
<script type="text/javascript">
	$(".room form").submit(function() {
        var $this = $(this);
		$.post(this.action, $(this).serialize(), function(data){
            $this.parents('.content').html(data);
        });
        return false;
	});
    $('input[type=button], input[type=submit]').button();
</script>