<ul>
	<?php foreach( $this->rs as $rs ):?>
		<li>
			<?php echo $this->image( "icones/chat_status_" . $rs['status'] . ".gif" )?>
			
			<a href="#open" onclick="Chat.open( '<?php echo $rs['status']?>' , <?php echo $rs['personid']?> );"><?php echo $this->translate( $rs['acname'] )?> - <?php echo $this->shortName( $rs['name'] )?></a>
			
			<div id="chat-users-list-<?php echo $rs['personid']?>" style="display: none;">
				<img src="<?php echo $this->url?>/upload/thumb_small<?php echo $rs['location']?>" />
				<span><?php echo $this->translate( $rs['acname'] )?> - <?php echo $this->shortName( $rs['name'] )?></span>
			</div>
		</li>
	<?php endforeach ?>
</ul>
<script>
	Chat.load( '<?php echo $this->messages?>' );
</script>